<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Tnosc.EShop.Agent.Application\Tnosc.EShop.Agent.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Agents.AI" />
    <PackageReference Include="Microsoft.Agents.AI.Foundry" />
    <PackageReference Include="Microsoft.Extensions.AI" />
    <PackageReference Include="Azure.AI.Projects" />
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Tnosc.EShop.Agent.Tests.Unit" />
  </ItemGroup>
</Project>
