<Project Sdk="Aspire.AppHost.Sdk/13.5.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>2d34ade3-0fcc-417f-a3e9-f0827773adeb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\client\Tnosc.EShop.Client.Web\Tnosc.EShop.Client.Web\Tnosc.EShop.Client.Web.csproj" />
    <ProjectReference Include="..\..\src\mcp\Tnosc.EShop.Mcp.Host\Tnosc.EShop.Mcp.Host.csproj" />
    <ProjectReference Include="..\..\src\server\Tnosc.EShop.Server.Host\Tnosc.EShop.Server.Host.csproj" />
    <ProjectReference Include="..\Tnosc.EShop.ServiceDefaults\Tnosc.EShop.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.Keycloak" />
    <PackageReference Include="Aspire.Hosting.Redis" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.McpInspector" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Realms\**\*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
