<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<ProjectReference Include="..\Tnosc.Lib.Application\Tnosc.Lib.Application.csproj" />
	</ItemGroup>
</Project>
