// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tnosc.EShop.Server.Infrastructure.Persistence.Contexts;

#nullable disable

namespace Tnosc.EShop.Server.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EShopWriteDbContext))]
    [Migration("20260810092508_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation(annotation: "ProductVersion", value: "10.0.10")
                .HasAnnotation(annotation: "Relational:MaxIdentifierLength", value: 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder: modelBuilder);

            modelBuilder.Entity(name: "Tnosc.Lib.Infrastructure.Persistence.Outbox.OutboxMessage", buildAction: b =>
                {
                    b.Property<Guid>(propertyName: "Id")
                        .HasColumnType(typeName: "uuid")
                        .HasColumnName(name: "id");

                    b.Property<int>(propertyName: "Attempts")
                        .HasColumnType(typeName: "integer")
                        .HasColumnName(name: "attempts");

                    b.Property<string>(propertyName: "Content")
                        .IsRequired()
                        .HasColumnType(typeName: "jsonb")
                        .HasColumnName(name: "content");

                    b.Property<string>(propertyName: "Error")
                        .HasMaxLength(maxLength: 4000)
                        .HasColumnType(typeName: "character varying(4000)")
                        .HasColumnName(name: "error");

                    b.Property<DateTime?>(propertyName: "NextAttemptOnUtc")
                        .HasColumnType(typeName: "timestamp with time zone")
                        .HasColumnName(name: "next_attempt_on_utc");

                    b.Property<DateTime>(propertyName: "OccurredOnUtc")
                        .HasColumnType(typeName: "timestamp with time zone")
                        .HasColumnName(name: "occurred_on_utc");

                    b.Property<DateTime?>(propertyName: "ProcessedOnUtc")
                        .HasColumnType(typeName: "timestamp with time zone")
                        .HasColumnName(name: "processed_on_utc");

                    b.Property<string>(propertyName: "Type")
                        .IsRequired()
                        .HasMaxLength(maxLength: 256)
                        .HasColumnType(typeName: "character varying(256)")
                        .HasColumnName(name: "type");

                    b.HasKey(propertyNames: "Id");

                    b.HasIndex("NextAttemptOnUtc", "OccurredOnUtc")
                        .HasDatabaseName(name: "ix_outbox_messages_pending")
                        .HasFilter(sql: "processed_on_utc IS NULL");

                    b.ToTable(name: "outbox_messages", schema: "outbox");
                });
#pragma warning restore 612, 618
        }
    }
}
