<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="ModelContextProtocol.AspNetCore" />
    <PackageReference Include="Aspire.Keycloak.Authentication" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\aspire\Tnosc.EShop.ServiceDefaults\Tnosc.EShop.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Tnosc.EShop.Mcp.Tool\Tnosc.EShop.Mcp.Tool.csproj" />
    <ProjectReference Include="..\Tnosc.EShop.Mcp.Infrastructure.External\Tnosc.EShop.Mcp.Infrastructure.External.csproj" />
  </ItemGroup>
</Project>
